# test/Dockerfile.tests
FROM python:3.12-slim
ENV PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl build-essential \
 && rm -rf /var/lib/apt/lists/*

# Copy base + dev reqs first (lepszy cache warstw)
COPY requirements.txt .
COPY test/requirements-dev.txt test/requirements-dev.txt
RUN pip install -r test/requirements-dev.txt

COPY . .

# Domyślnie używamy ustawień z test/pytest.ini
CMD ["pytest", "-q", "-c", "test/pytest.ini"]
