# test\selenium\test_CheckMoreStats.py
# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

BASE_URL = "http://127.0.0.1:5000/player_stats/HextechChest--202/eu-west"

class TestCheckMoreStats:
    """End-to-End test for expanding and collapsing match statistics details.

    Steps:
      1) Open a player's stats page with match history.
      2) Click on the first match's "Show Stats" button.
      3) Wait for the detailed stats panel to become visible.
      4) Verify key stat fields (KDA, CS, Items) are present.
      5) Click the button again to collapse; verify hidden.
    """

    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.wait = WebDriverWait(self.driver, 15)

    def teardown_method(self, method):
        self.driver.quit()

    def test_expand_collapse_stats(self):
        self.driver.get(BASE_URL)
        self.driver.set_window_size(1936, 1096)

        self.wait.until(EC.title_is("Player History"))

        toggle = self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button.toggle-details")))
        panel = toggle.find_element(
            By.XPATH,
            "ancestor::div[contains(@class,'card')]//div[contains(@class,'row') and contains(@class,'margin-0')]",
        )

        assert not panel.is_displayed()

        toggle.click()
        self.wait.until(lambda d: panel.is_displayed())

        assert "KDA" in panel.text and "CS" in panel.text and "Items" in panel.text
        assert len(panel.find_elements(By.CSS_SELECTOR, "img.array-icon-1")) > 0

        toggle.click()
        self.wait.until(lambda d: not panel.is_displayed())
