# test\selenium\test_testSearchBar.py
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestSearchBar():
  """
  End-to-End test for the search bar functionality:
  1. Open the home page.
  2. Wait for the server dropdown to be visible.
  3. Select a server from the dropdown.
  4. Enter a valid summoner name into the text field.
  5. Click the search button.
  6. Verify that the browser redirects to the expected player stats URL.
  """
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testSearchBar(self):
    self.driver.get("http://127.0.0.1:5000")
    self.driver.set_window_size(1936, 1096)
    self.driver.find_element(By.ID, "lista").click()
    dropdown = self.driver.find_element(By.ID, "lista")
    dropdown.find_element(By.XPATH, "//option[. = 'eu west']").click()
    self.driver.find_element(By.ID, "tekst").click()
    self.driver.find_element(By.ID, "tekst").send_keys("HextechChest#202")
    self.driver.find_element(By.ID, "Search_button").click()
  
