# test\selenium\test_testCheckMoreStats.py
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestCheckMoreStats():
  """
  End-to-End test for expanding and collapsing match statistics details:
  1. Open a player's stats page with match history.
  2. Click on the first match's "Show Stats" button.
  3. Wait for the detailed stats panel to become visible.
  4. Verify that key stat fields (e.g., KDA, Items) are present.
  5. Click the button again to collapse the stats.
  6. Confirm that the detailed panel is hidden.
  """
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testCheckMoreStats(self):
    self.driver.get("http://127.0.0.1:5000/player_stats/HextechChest--202/eu-west")
    self.driver.set_window_size(1936, 1096)
    self.driver.find_element(By.ID, "All-Player-Button-Match-1").click()
    self.driver.find_element(By.ID, "All-Player-Button-Match-2").click()
    self.driver.find_element(By.ID, "All-Player-Button-Match-2").click()
    self.driver.find_element(By.ID, "All-Player-Button-Match-1").click()
  
